version: '3.8'

services:
  # Redis pour le cache et la queue
  redis:
    image: redis:7-alpine
    container_name: 3cx-ninja-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Serveur principal 3CX-Ninja
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 3cx-ninja-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - ./temp:/app/temp
      - whisper-models:/app/models
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Dashboard web (optionnel en dev)
  dashboard:
    profiles: ["dev"]
    build:
      context: ./dashboard
      dockerfile: Dockerfile.dev
    container_name: 3cx-ninja-dashboard
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    depends_on:
      - server
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  whisper-models:
    driver: local

networks:
  default:
    name: 3cx-ninja-network